name: Clear commits
on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *"
  push:
    branches:
      - 'master'
    paths:
      - '.github/**/*.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: commit
        run: |
          git init
          git config --local user.name "actions"
          git config --local user.email "action@github.com"
          git checkout --orphan clearhistory
          git branch -D master
          git checkout --orphan master
          git add .
          git commit -m "🚀 CI Updated"
          git remote set-url --add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin master
